version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "passwordless-signin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cdbcmpyku0o2"
s3_prefix = "passwordless-signin"
region = "ap-northeast-1"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolName=\"passwordless-signin\" SESFromAddress=\"vegertar@gmail.com\""
image_repositories = []
